import { CartSheet } from "@/components/cart/cart-sheet";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { Header } from "@/components/layout/header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Providers } from "@/providers/providers";
import type { Metadata } from "next";
import { Delius_Swash_Caps } from "next/font/google";
import "./globals.css";

const deliusSwashCaps = Delius_Swash_Caps({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Ecommerce Product Listing and Shopping Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${deliusSwashCaps.className} antialiased`}>
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <Header />
              <main className="flex-1 p-4">{children}</main>
            </SidebarInset>
          </SidebarProvider>
          <CartSheet />
        </Providers>
      </body>
    </html>
  );
}
